server:
  port: 8082

spring:
  application:
    name: order-service

  datasource:
    url: jdbc:postgresql://${PGHOST}:${PGPORT}/railway?sslmode=disable
    username: ${PGUSER}       # "postgres" (default)
    password: ${PGPASSWORD}   # Railway auto-generates this
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
